/**
 * Represents a single planned action emitted by the Planner node.
 * Kept intentionally open (index signature) because different action types
 * carry different fields, and third-party skills may extend this at runtime.
 */
export interface PlannedAction {
  type: string;
  skill_name?: string;
  params?: Record<string, unknown>;
  description?: string;
  intent?: string;
  task_type?: string;
  requires_human?: boolean;
  human_type?: "confirmation" | "login" | "captcha" | "2fa" | "stuck";
  human_message?: string;
  /** memorize action key */
  key?: string;
  /** memorize action value */
  value?: unknown;
  /** ui_interact text input */
  text?: string;
  /** finish action result message */
  result?: string;
  /** finish action summary */
  summary?: string;
  task_list?: Array<{ id?: string; status: string; goal: string }>;
}

export interface ExecutionResult {
  success: boolean;
  error?: string;
  reason?: string;
  message?: string;
  skill_result?: Record<string, any> | null;
  manual_content?: string;
  text_content?: string;
  screenshot?: string | null;
}

/**
 * A single entry in the agent execution history (total_history).
 */
export interface HistoryStep {
  step: number;
  action: PlannedAction;
  result: ExecutionResult | null;
  /** Human-readable summary generated by Watchdog after execution. */
  step_summary?: string;
  meta?: Record<string, unknown>;
}
