// config keys
export const MIDSCENE_MODEL_INIT_CONFIG_JSON = 'MIDSCENE_MODEL_INIT_CONFIG_JSON';
export const MIDSCENE_MODEL_NAME = 'MIDSCENE_MODEL_NAME';
export const MIDSCENE_DEBUG_MODEL_PROFILE = 'MIDSCENE_DEBUG_MODEL_PROFILE';
export const MIDSCENE_DEBUG_MODEL_RESPONSE = 'MIDSCENE_DEBUG_MODEL_RESPONSE';
export const MIDSCENE_DANGEROUSLY_PRINT_ALL_CONFIG = 'MIDSCENE_DANGEROUSLY_PRINT_ALL_CONFIG';
export const MIDSCENE_DEBUG_MODE = 'MIDSCENE_DEBUG_MODE';
export const MIDSCENE_MCP_USE_PUPPETEER_MODE = 'MIDSCENE_MCP_USE_PUPPETEER_MODE';
export const MIDSCENE_MCP_CHROME_PATH = 'MIDSCENE_MCP_CHROME_PATH';
export const MIDSCENE_MCP_ANDROID_MODE = 'MIDSCENE_MCP_ANDROID_MODE';
export const DOCKER_CONTAINER = 'DOCKER_CONTAINER';
// Observability
export const MIDSCENE_LANGSMITH_DEBUG = 'MIDSCENE_LANGSMITH_DEBUG';
export const MIDSCENE_LANGFUSE_DEBUG = 'MIDSCENE_LANGFUSE_DEBUG';
export const MIDSCENE_MODEL_SOCKS_PROXY = 'MIDSCENE_MODEL_SOCKS_PROXY';
export const MIDSCENE_MODEL_HTTP_PROXY = 'MIDSCENE_MODEL_HTTP_PROXY';
// New primary names for public API
export const MIDSCENE_MODEL_API_KEY = 'MIDSCENE_MODEL_API_KEY';
export const MIDSCENE_MODEL_BASE_URL = 'MIDSCENE_MODEL_BASE_URL';
export const MIDSCENE_MODEL_MAX_TOKENS = 'MIDSCENE_MODEL_MAX_TOKENS';
export const MIDSCENE_MODEL_TIMEOUT = 'MIDSCENE_MODEL_TIMEOUT';
export const MIDSCENE_MODEL_TEMPERATURE = 'MIDSCENE_MODEL_TEMPERATURE';
export const MIDSCENE_MODEL_RETRY_COUNT = 'MIDSCENE_MODEL_RETRY_COUNT';
export const MIDSCENE_MODEL_RETRY_INTERVAL = 'MIDSCENE_MODEL_RETRY_INTERVAL';
export const MIDSCENE_MODEL_REASONING_EFFORT = 'MIDSCENE_MODEL_REASONING_EFFORT';
export const MIDSCENE_MODEL_REASONING_ENABLED = 'MIDSCENE_MODEL_REASONING_ENABLED';
export const MIDSCENE_MODEL_REASONING_BUDGET = 'MIDSCENE_MODEL_REASONING_BUDGET';
/**
 * @deprecated Use MIDSCENE_MODEL_API_KEY instead. This is kept for backward compatibility.
 */
export const OPENAI_API_KEY = 'OPENAI_API_KEY';
/**
 * @deprecated Use MIDSCENE_MODEL_BASE_URL instead. This is kept for backward compatibility.
 */
export const OPENAI_BASE_URL = 'OPENAI_BASE_URL';
/**
 * @deprecated Use MIDSCENE_MODEL_INIT_CONFIG_JSON instead. This is kept for backward compatibility.
 */
export const MIDSCENE_OPENAI_INIT_CONFIG_JSON = 'MIDSCENE_OPENAI_INIT_CONFIG_JSON';
/**
 * @deprecated Use MIDSCENE_MODEL_HTTP_PROXY instead. This is kept for backward compatibility.
 */
export const MIDSCENE_OPENAI_HTTP_PROXY = 'MIDSCENE_OPENAI_HTTP_PROXY';
/**
 * @deprecated Use MIDSCENE_MODEL_SOCKS_PROXY instead. This is kept for backward compatibility.
 */
export const MIDSCENE_OPENAI_SOCKS_PROXY = 'MIDSCENE_OPENAI_SOCKS_PROXY';
/**
 * @deprecated Use MIDSCENE_MODEL_MAX_TOKENS instead. This is kept for backward compatibility.
 */
export const OPENAI_MAX_TOKENS = 'OPENAI_MAX_TOKENS';
export const MIDSCENE_ADB_PATH = 'MIDSCENE_ADB_PATH';
export const MIDSCENE_ADB_REMOTE_HOST = 'MIDSCENE_ADB_REMOTE_HOST';
export const MIDSCENE_ADB_REMOTE_PORT = 'MIDSCENE_ADB_REMOTE_PORT';
export const MIDSCENE_ANDROID_IME_STRATEGY = 'MIDSCENE_ANDROID_IME_STRATEGY';
export const MIDSCENE_IOS_DEVICE_UDID = 'MIDSCENE_IOS_DEVICE_UDID';
export const MIDSCENE_IOS_SIMULATOR_UDID = 'MIDSCENE_IOS_SIMULATOR_UDID';
export const MIDSCENE_CACHE = 'MIDSCENE_CACHE';
export const MIDSCENE_USE_VLM_UI_TARS = 'MIDSCENE_USE_VLM_UI_TARS';
export const MIDSCENE_USE_QWEN_VL = 'MIDSCENE_USE_QWEN_VL';
export const MIDSCENE_USE_QWEN3_VL = 'MIDSCENE_USE_QWEN3_VL';
export const MIDSCENE_USE_DOUBAO_VISION = 'MIDSCENE_USE_DOUBAO_VISION';
export const MIDSCENE_USE_GEMINI = 'MIDSCENE_USE_GEMINI';
export const MIDSCENE_USE_VL_MODEL = 'MIDSCENE_USE_VL_MODEL';
export const MATCH_BY_POSITION = 'MATCH_BY_POSITION';
export const MIDSCENE_REPORT_TAG_NAME = 'MIDSCENE_REPORT_TAG_NAME';
export const MIDSCENE_REPORT_QUIET = 'MIDSCENE_REPORT_QUIET';
export const MIDSCENE_PREFERRED_LANGUAGE = 'MIDSCENE_PREFERRED_LANGUAGE';
export const MIDSCENE_CACHE_MAX_FILENAME_LENGTH = 'MIDSCENE_CACHE_MAX_FILENAME_LENGTH';
export const MIDSCENE_REPLANNING_CYCLE_LIMIT = 'MIDSCENE_REPLANNING_CYCLE_LIMIT';
export const MIDSCENE_RUN_DIR = 'MIDSCENE_RUN_DIR';
// INSIGHT (unified VQA and Grounding)
export const MIDSCENE_INSIGHT_MODEL_NAME = 'MIDSCENE_INSIGHT_MODEL_NAME';
export const MIDSCENE_INSIGHT_MODEL_SOCKS_PROXY = 'MIDSCENE_INSIGHT_MODEL_SOCKS_PROXY';
export const MIDSCENE_INSIGHT_MODEL_HTTP_PROXY = 'MIDSCENE_INSIGHT_MODEL_HTTP_PROXY';
export const MIDSCENE_INSIGHT_MODEL_BASE_URL = 'MIDSCENE_INSIGHT_MODEL_BASE_URL';
export const MIDSCENE_INSIGHT_MODEL_API_KEY = 'MIDSCENE_INSIGHT_MODEL_API_KEY';
export const MIDSCENE_INSIGHT_MODEL_INIT_CONFIG_JSON = 'MIDSCENE_INSIGHT_MODEL_INIT_CONFIG_JSON';
export const MIDSCENE_INSIGHT_MODEL_TIMEOUT = 'MIDSCENE_INSIGHT_MODEL_TIMEOUT';
export const MIDSCENE_INSIGHT_MODEL_TEMPERATURE = 'MIDSCENE_INSIGHT_MODEL_TEMPERATURE';
export const MIDSCENE_INSIGHT_MODEL_RETRY_COUNT = 'MIDSCENE_INSIGHT_MODEL_RETRY_COUNT';
export const MIDSCENE_INSIGHT_MODEL_RETRY_INTERVAL = 'MIDSCENE_INSIGHT_MODEL_RETRY_INTERVAL';
export const MIDSCENE_INSIGHT_MODEL_FAMILY = 'MIDSCENE_INSIGHT_MODEL_FAMILY';
export const MIDSCENE_INSIGHT_MODEL_REASONING_EFFORT = 'MIDSCENE_INSIGHT_MODEL_REASONING_EFFORT';
export const MIDSCENE_INSIGHT_MODEL_REASONING_ENABLED = 'MIDSCENE_INSIGHT_MODEL_REASONING_ENABLED';
export const MIDSCENE_INSIGHT_MODEL_REASONING_BUDGET = 'MIDSCENE_INSIGHT_MODEL_REASONING_BUDGET';
// PLANNING
export const MIDSCENE_PLANNING_MODEL_NAME = 'MIDSCENE_PLANNING_MODEL_NAME';
export const MIDSCENE_PLANNING_MODEL_SOCKS_PROXY = 'MIDSCENE_PLANNING_MODEL_SOCKS_PROXY';
export const MIDSCENE_PLANNING_MODEL_HTTP_PROXY = 'MIDSCENE_PLANNING_MODEL_HTTP_PROXY';
export const MIDSCENE_PLANNING_MODEL_BASE_URL = 'MIDSCENE_PLANNING_MODEL_BASE_URL';
export const MIDSCENE_PLANNING_MODEL_API_KEY = 'MIDSCENE_PLANNING_MODEL_API_KEY';
export const MIDSCENE_PLANNING_MODEL_INIT_CONFIG_JSON = 'MIDSCENE_PLANNING_MODEL_INIT_CONFIG_JSON';
export const MIDSCENE_PLANNING_MODEL_TIMEOUT = 'MIDSCENE_PLANNING_MODEL_TIMEOUT';
export const MIDSCENE_PLANNING_MODEL_TEMPERATURE = 'MIDSCENE_PLANNING_MODEL_TEMPERATURE';
export const MIDSCENE_PLANNING_MODEL_RETRY_COUNT = 'MIDSCENE_PLANNING_MODEL_RETRY_COUNT';
export const MIDSCENE_PLANNING_MODEL_RETRY_INTERVAL = 'MIDSCENE_PLANNING_MODEL_RETRY_INTERVAL';
export const MIDSCENE_PLANNING_MODEL_FAMILY = 'MIDSCENE_PLANNING_MODEL_FAMILY';
export const MIDSCENE_PLANNING_MODEL_REASONING_EFFORT = 'MIDSCENE_PLANNING_MODEL_REASONING_EFFORT';
export const MIDSCENE_PLANNING_MODEL_REASONING_ENABLED = 'MIDSCENE_PLANNING_MODEL_REASONING_ENABLED';
export const MIDSCENE_PLANNING_MODEL_REASONING_BUDGET = 'MIDSCENE_PLANNING_MODEL_REASONING_BUDGET';
export const MIDSCENE_MODEL_FAMILY = 'MIDSCENE_MODEL_FAMILY';
/**
 * env keys declared but unused
 */
export const UNUSED_ENV_KEYS = [MIDSCENE_DANGEROUSLY_PRINT_ALL_CONFIG];
/**
 * env keys for debug or basic run
 * can not be override by overrideAIConfig
 */
export const BASIC_ENV_KEYS = [
    MIDSCENE_DEBUG_MODE,
    MIDSCENE_DEBUG_MODEL_PROFILE,
    MIDSCENE_DEBUG_MODEL_RESPONSE,
    MIDSCENE_RUN_DIR,
];
export const BOOLEAN_ENV_KEYS = [
    MIDSCENE_CACHE,
    MIDSCENE_MCP_USE_PUPPETEER_MODE,
    MIDSCENE_MCP_ANDROID_MODE,
    MIDSCENE_LANGSMITH_DEBUG,
    MIDSCENE_LANGFUSE_DEBUG,
    MIDSCENE_REPORT_QUIET,
];
export const NUMBER_ENV_KEYS = [
    MIDSCENE_MODEL_MAX_TOKENS,
    MIDSCENE_CACHE_MAX_FILENAME_LENGTH,
    MIDSCENE_REPLANNING_CYCLE_LIMIT,
];
export const STRING_ENV_KEYS = [
    MIDSCENE_MODEL_MAX_TOKENS,
    OPENAI_MAX_TOKENS,
    MIDSCENE_ADB_PATH,
    MIDSCENE_ADB_REMOTE_HOST,
    MIDSCENE_ADB_REMOTE_PORT,
    MIDSCENE_ANDROID_IME_STRATEGY,
    MIDSCENE_IOS_DEVICE_UDID,
    MIDSCENE_IOS_SIMULATOR_UDID,
    MIDSCENE_REPORT_TAG_NAME,
    MIDSCENE_PREFERRED_LANGUAGE,
    MATCH_BY_POSITION,
    MIDSCENE_MCP_CHROME_PATH,
    DOCKER_CONTAINER,
];
/**
 * Non model related env keys, used for globally controlling the behavior of midscene
 * Can not be override by agent.modelConfig but can be override by overrideAIConfig
 * Can be access at any time
 */
export const GLOBAL_ENV_KEYS = [
    ...BOOLEAN_ENV_KEYS,
    ...NUMBER_ENV_KEYS,
    ...STRING_ENV_KEYS,
];
/**
 * Model related eve keys, used for declare which model to use.
 * Can be override by both agent.modelConfig and overrideAIConfig
 * Can only be access after agent.constructor
 */
export const MODEL_ENV_KEYS = [
    // model default
    MIDSCENE_MODEL_NAME,
    MIDSCENE_MODEL_INIT_CONFIG_JSON,
    MIDSCENE_MODEL_API_KEY,
    MIDSCENE_MODEL_BASE_URL,
    MIDSCENE_MODEL_SOCKS_PROXY,
    MIDSCENE_MODEL_HTTP_PROXY,
    MIDSCENE_MODEL_TIMEOUT,
    MIDSCENE_MODEL_TEMPERATURE,
    MIDSCENE_MODEL_RETRY_COUNT,
    MIDSCENE_MODEL_RETRY_INTERVAL,
    MIDSCENE_MODEL_REASONING_EFFORT,
    MIDSCENE_MODEL_REASONING_ENABLED,
    MIDSCENE_MODEL_REASONING_BUDGET,
    MIDSCENE_USE_VLM_UI_TARS,
    MIDSCENE_USE_QWEN_VL,
    MIDSCENE_USE_QWEN3_VL,
    MIDSCENE_USE_DOUBAO_VISION,
    MIDSCENE_USE_GEMINI,
    MIDSCENE_USE_VL_MODEL,
    // model default legacy
    OPENAI_API_KEY,
    OPENAI_BASE_URL,
    MIDSCENE_OPENAI_INIT_CONFIG_JSON,
    MIDSCENE_OPENAI_HTTP_PROXY,
    MIDSCENE_OPENAI_SOCKS_PROXY,
    // INSIGHT (unified VQA and Grounding)
    MIDSCENE_INSIGHT_MODEL_NAME,
    MIDSCENE_INSIGHT_MODEL_SOCKS_PROXY,
    MIDSCENE_INSIGHT_MODEL_HTTP_PROXY,
    MIDSCENE_INSIGHT_MODEL_BASE_URL,
    MIDSCENE_INSIGHT_MODEL_API_KEY,
    MIDSCENE_INSIGHT_MODEL_INIT_CONFIG_JSON,
    MIDSCENE_INSIGHT_MODEL_TIMEOUT,
    MIDSCENE_INSIGHT_MODEL_TEMPERATURE,
    MIDSCENE_INSIGHT_MODEL_RETRY_COUNT,
    MIDSCENE_INSIGHT_MODEL_RETRY_INTERVAL,
    MIDSCENE_INSIGHT_MODEL_FAMILY,
    MIDSCENE_INSIGHT_MODEL_REASONING_EFFORT,
    MIDSCENE_INSIGHT_MODEL_REASONING_ENABLED,
    MIDSCENE_INSIGHT_MODEL_REASONING_BUDGET,
    // PLANNING
    MIDSCENE_PLANNING_MODEL_NAME,
    MIDSCENE_PLANNING_MODEL_SOCKS_PROXY,
    MIDSCENE_PLANNING_MODEL_HTTP_PROXY,
    MIDSCENE_PLANNING_MODEL_BASE_URL,
    MIDSCENE_PLANNING_MODEL_API_KEY,
    MIDSCENE_PLANNING_MODEL_INIT_CONFIG_JSON,
    MIDSCENE_PLANNING_MODEL_TIMEOUT,
    MIDSCENE_PLANNING_MODEL_TEMPERATURE,
    MIDSCENE_PLANNING_MODEL_RETRY_COUNT,
    MIDSCENE_PLANNING_MODEL_RETRY_INTERVAL,
    MIDSCENE_PLANNING_MODEL_FAMILY,
    MIDSCENE_PLANNING_MODEL_REASONING_EFFORT,
    MIDSCENE_PLANNING_MODEL_REASONING_ENABLED,
    MIDSCENE_PLANNING_MODEL_REASONING_BUDGET,
    MIDSCENE_MODEL_FAMILY,
];
export const ALL_ENV_KEYS = [
    ...UNUSED_ENV_KEYS,
    ...BASIC_ENV_KEYS,
    ...GLOBAL_ENV_KEYS,
    ...MODEL_ENV_KEYS,
];
export const VL_MODE_RAW_VALID_VALUES = [
    'doubao-vision',
    'doubao-seed',
    'gemini',
    'qwen2.5-vl',
    'qwen3-vl',
    'qwen3.5',
    'vlm-ui-tars',
    'vlm-ui-tars-doubao',
    'vlm-ui-tars-doubao-1.5',
    'glm-v',
    'auto-glm',
    'auto-glm-multilingual',
];
export const MODEL_FAMILY_VALUES = [
    ...VL_MODE_RAW_VALID_VALUES,
    'gpt-5',
];
export var UITarsModelVersion;
(function (UITarsModelVersion) {
    UITarsModelVersion["V1_0"] = "1.0";
    UITarsModelVersion["V1_5"] = "1.5";
    UITarsModelVersion["DOUBAO_1_5_15B"] = "doubao-1.5-15B";
    UITarsModelVersion["DOUBAO_1_5_20B"] = "doubao-1.5-20B";
})(UITarsModelVersion || (UITarsModelVersion = {}));
