/**
 * CoTabor Tri-level Memory Types
 * Definition for L1, L2, L3 and SyncQueue schemas
 */

export type MemoryLevel = 'L1' | 'L2' | 'L3';

// L1: Muscle Memory (DOM/Physical interactions)
export interface L1MuscleMemory {
  id: string; // e.g. mus_1001
  domain: string; // Target domain, e.g. github.com
  pathPattern: string; // Target path pattern, e.g. ^/pulls/.*
  elementSelector: string; // DOM Hash or Selector
  actionType: 'click' | 'input' | 'scroll' | 'hover' | 'wait' | string;
  physicalInstruction: string; // JSON string of execution parameters (e.g. CDP offset)
  reason?: string; // AI generated reason for the rescue
  executionCount: number; // Total times triggered
  successCount: number; // Times execution succeeded
  updatedAt: number; // Timestamp
  // Ebbinghaus forgetting curve fields
  stability?: number; // Stability in days (init 2, grows ×1.5 per hit, max 90)
  lastAccessedAt?: number; // Timestamp of last retrieval hit
}

// L2: Skill Schema Memory (API parameter fixing rules)
export interface L2SkillMemory {
  id: string; // e.g. skl_2001
  skillName: string; // Tool/Skill name, e.g. feishu_create_doc
  ruleType?: string; // Optional classification for the rule, e.g. param_format
  contextScope?: string; // Optional scope, e.g. notion_db_init
  /** 'base' = universal rule (no taskType); 'contextual' = specific to a taskType */
  ruleScope?: 'base' | 'contextual';
  parameterRules: string; // LLM combined string of rules to avoid errors
  errorHistory?: string; // Past real errors encountered
  hitCount?: number;
  successCount?: number;
  status: 'active' | 'archived' | 'needs_review';
  updatedAt: number; // Timestamp
  // Ebbinghaus forgetting curve fields
  stability?: number; // Stability in days (init 2, grows ×1.5 per hit, max 90)
  lastAccessedAt?: number; // Timestamp of last retrieval hit
}

// L3: Tactical Memory (Macro SOPs)
export interface L3TacticalMemory {
  id: string; // e.g. tac_3001
  intentQuery: string; // Intent summary for retrieval
  memoryTitle: string; // Short retrievable title for BM25
  taskType?: string;
  domainScope?: string;
  language?: string;
  keywords?: string[];
  tacticalRules: string; // The SOP steps
  updatedAt: number; // Timestamp
  usageCount?: number;
  successCount?: number;
  /** IDs of semantically similar L3 memories found at write time (A-MEM style linking) */
  relatedMemoryIds?: string[];
  /** 'positive' = success pattern, 'anti_pattern' = failure lesson to avoid */
  memoryType?: 'positive' | 'anti_pattern';
  // Ebbinghaus forgetting curve fields
  stability?: number; // Stability in days (init 2, grows ×1.5 per hit, max 90)
  lastAccessedAt?: number; // Timestamp of last retrieval hit
}

// Unified Sync Queue Entry
export interface SyncQueueEntry {
  id: string; // UUID for the queue entry
  action: 'insert' | 'update' | 'delete';
  memoryLevel: MemoryLevel;
  targetId: string; // The ID in the target table (mus_*, skl_*, tac_*)
  payload: any; // The full record data
  queuedAt: number; // Timestamp
  retryCount?: number; // Number of failed push attempts; entry dropped after 3
  status?: 'pending' | 'failed';
  lastError?: string;
  lastAttemptAt?: number;
}

// Raw Trace (New experience generated by Cortex/Watchdog before distillation)
export interface RawExperienceTrace {
  id: string;
  memoryLevel: MemoryLevel;
  context: Record<string, any>; // url, path, element, error message, etc.
  suggestedCorrection: string | Record<string, any>; // The fix applied
  success: boolean; // Did the fix work?
  timestamp: number;
}

export interface TaskExperienceBuffer {
  site_insights: Array<{ domain: string; content: string }>;
  tool_insights: Array<{ skillName: string; content: string }>;
  task_wisdom: Array<string>;
  /** Anti-patterns extracted from failed tasks only. Each item is an explicit "don't do X" instruction. */
  failure_insights?: Array<string>;
}

export interface MemoryCandidate {
  id: string;
  source: 'site_insight' | 'tool_insight' | 'task_wisdom' | 'history_fallback' | 'failure_insight';
  text: string;
  goal: string;
  domain?: string;
  path?: string;
  skillName?: string;
  evidence?: string[];
  sourceTraceIds?: string[];
  /** True when this candidate was extracted from a failed task's failure_insights */
  isAntiPattern?: boolean;
}

export interface ClassifiedMemory {
  candidateId: string;
  level: MemoryLevel | 'DROP';
  title: string;
  memoryText: string;
  reason: string;
  confidence: number;
  keywords?: string[];
  language?: string;
  domainScope?: string;
  scope: {
    domain?: string;
    path?: string;
    skillName?: string;
    taskType?: string;
  };
  /** Propagated from MemoryCandidate; drives L3 storage as anti_pattern */
  memoryType?: 'positive' | 'anti_pattern';
}

export interface MemoryRefRecord {
  id: string;
  level: MemoryLevel;
  title: string;
  memoryText?: string;
}

export interface CommittedMemoryDetail {
  id: string;
  level: MemoryLevel;
  title: string;
  memoryText: string;
}

export interface ExperienceSyncItemStatus {
  status: 'pending' | 'synced' | 'failed';
  error?: string;
}

export interface ExperienceSyncDetails {
  taskRuns: ExperienceSyncItemStatus;
  rawTraces: ExperienceSyncItemStatus & {
    syncedCount?: number;
    failedCount?: number;
    pendingCount?: number;
  };
  notionSync?: ExperienceSyncItemStatus & {
    issues?: string[];
  };
}

export interface TaskMemoryCommitInput {
  goal: string;
  finalState: {
    /** Pre-generated task run ID from agent.ts; scheduler uses this instead of generating its own. */
    task_run_id?: string;
    total_history?: any[];
    long_term_memory?: { summary?: string };
    experience_buffer?: TaskExperienceBuffer;
    meta_data?: Record<string, any>;
    status?: string;
    planner_output?: { action?: Record<string, any> };
  };
}

export interface TaskMemoryCommitResult {
  taskRunId?: string;
  taskRunSynced?: boolean;
  scheduled?: boolean;
  experienceStatus?: 'PENDING' | 'RUNNING' | 'SUCCEEDED' | 'FAILED';
  candidates: number;
  committedMemories?: CommittedMemoryDetail[];
  syncDetails?: ExperienceSyncDetails;
  committed: {
    L1: number;
    L2: number;
    L3: number;
    DROP: number;
  };
}

export interface RawTraceRecord {
  traceId: string;
  taskRunId: string;
  timestamp: number;
  stepIndex: number;
  nodeName?: string;
  actionType?: string;
  skillName?: string;
  success?: boolean;
  url?: string;
  domain?: string;
  path?: string;
  pageTitle?: string;
  stepSummary?: string;
  errorMessage?: string;
  memoryRefs?: MemoryRefRecord[];
  syncStatus?: 'pending' | 'synced' | 'failed';
  syncError?: string;
  syncRetryCount?: number;
  lastSyncAttemptAt?: number;
  syncedAt?: number;
  updatedAt?: number;
  raw: any;
}

export interface MemoryWriteResult {
  level: MemoryLevel | 'DROP';
  ref?: MemoryRefRecord;
}

/**
 * Score breakdown for a single L3 retrieval result.
 * Each factor is surfaced separately for debuggability and future A/B testing.
 */
export interface L3ScoreBreakdown {
  bm25: number;
  domainBonus: number;
  taskTypeBonus: number;
  languageBonus: number;
  successBonus: number;
  usageBonus: number;
  /** Ebbinghaus retention score replacing the old binary freshnessBonus */
  retentionBonus: number;
}

/** A ranked L3 retrieval result that carries score information alongside the memory. */
export interface L3RetrievalMatch {
  memory: L3TacticalMemory;
  score: number;
  scoreBreakdown: L3ScoreBreakdown;
}

/** Semantic relationship type between two L3 memories. */
export type MemoryRelation =
  | 'refines'      // A is a more precise/accurate version of B (substitution)
  | 'extends'      // A adds new steps that B doesn't cover (additive)
  | 'contradicts'  // A and B give conflicting advice (surface both as warnings)
  | 'co_occurs'    // A and B are frequently retrieved in the same task (usage signal)
  | 'prerequisite';// Knowing B first is advised before applying A (ordering signal)

/**
 * A typed, weighted edge between two L3 memories in the knowledge graph.
 * Edges are stored as pairs (A→B and B→A) so lookups by either endpoint are O(1).
 * The canonical id uses the lexicographically smaller ID first to deduplicate.
 */
export interface MemoryEdge {
  id: string;                // `edge_${minId}_${maxId}`
  sourceId: string;          // Origin L3 memory
  targetId: string;          // Destination L3 memory
  relation: MemoryRelation;
  weight: number;            // 0.0–1.0; LLM-initialised at 0.6, co-occurrence grows it
  coOccurrenceCount: number; // How many tasks retrieved both memories
  createdAt: number;
  updatedAt: number;
}

/** Recognised by MemoryAttributionRecord */
export interface MemoryAttributionRecord {
  id: string;              // `attr_${taskRunId}_${memoryId}`
  taskRunId: string;
  memoryId: string;
  memoryLevel: MemoryLevel;
  retrievedAt: number;
  /** Filled in by the ExperienceJobWorker once the task outcome is known. */
  taskOutcome?: 'FINISHED' | 'FAILED';
}

export interface TaskRunRecord {
  id: string;
  goal: string;
  status: string;
  startedAt: number;
  finishedAt: number;
  hostUrl?: string;
  hostTitle?: string;
  globalSummary?: string;
  traceCount: number;
  candidateCount: number;
  committedL1: number;
  committedL2: number;
  committedL3: number;
  droppedCount: number;
  localPersistStatus: 'saved';
  experienceStatus: 'PENDING' | 'RUNNING' | 'SUCCEEDED' | 'FAILED';
  experienceStartedAt?: number;
  experienceFinishedAt?: number;
  experienceError?: string;
  experienceRetryCount: number;
  cloudSyncStatus: 'pending' | 'synced' | 'failed';
  cloudSyncError?: string;
  syncedAt?: number;
  updatedAt: number;
}
