/**
 * CoTabor Tri-level Memory Types
 * Definition for L1, L2, L3 and SyncQueue schemas
 */

export type MemoryLevel = 'L1' | 'L2' | 'L3';

// L1: Muscle Memory (DOM/Physical interactions)
export interface L1MuscleMemory {
  id: string; // e.g. mus_1001
  domain: string; // Target domain, e.g. github.com
  pathPattern: string; // Target path pattern, e.g. ^/pulls/.*
  elementSelector: string; // DOM Hash or Selector
  actionType: 'click' | 'input' | 'scroll' | 'hover' | 'wait' | string;
  physicalInstruction: string; // JSON string of execution parameters (e.g. CDP offset)
  reason?: string; // AI generated reason for the rescue
  executionCount: number; // Total times triggered
  successCount: number; // Times execution succeeded
  updatedAt: number; // Timestamp
}

// L2: Skill Schema Memory (API parameter fixing rules)
export interface L2SkillMemory {
  id: string; // e.g. skl_2001
  skillName: string; // Tool/Skill name, e.g. feishu_create_doc
  ruleType?: string; // Optional classification for the rule, e.g. param_format
  contextScope?: string; // Optional scope, e.g. notion_db_init
  parameterRules: string; // LLM combined string of rules to avoid errors
  errorHistory?: string; // Past real errors encountered
  hitCount?: number;
  successCount?: number;
  status: 'active' | 'archived' | 'needs_review';
  updatedAt: number; // Timestamp
}

// L3: Tactical Memory (Macro SOPs)
export interface L3TacticalMemory {
  id: string; // e.g. tac_3001
  intentQuery: string; // Intent summary for retrieval
  title: string; // Short retrievable title for BM25
  taskType?: string;
  domainScope?: string;
  language?: string;
  keywords?: string[];
  tacticalRules: string; // The SOP steps
  updatedAt: number; // Timestamp
  usageCount?: number;
  successCount?: number;
}

// Unified Sync Queue Entry
export interface SyncQueueEntry {
  id: string; // UUID for the queue entry
  action: 'insert' | 'update' | 'delete';
  memoryLevel: MemoryLevel;
  targetId: string; // The ID in the target table (mus_*, skl_*, tac_*)
  payload: any; // The full record data
  queuedAt: number; // Timestamp
  retryCount?: number; // Number of failed push attempts; entry dropped after 3
}

// Raw Trace (New experience generated by Cortex/Watchdog before distillation)
export interface RawExperienceTrace {
  id: string;
  memoryLevel: MemoryLevel;
  context: Record<string, any>; // url, path, element, error message, etc.
  suggestedCorrection: string | Record<string, any>; // The fix applied
  success: boolean; // Did the fix work?
  timestamp: number;
}

export interface TaskExperienceBuffer {
  site_insights: Array<{ domain: string; content: string }>;
  tool_insights: Array<{ skillName: string; content: string }>;
  task_wisdom: Array<string>;
}

export interface MemoryCandidate {
  id: string;
  source: 'site_insight' | 'tool_insight' | 'task_wisdom' | 'history_fallback';
  text: string;
  goal: string;
  domain?: string;
  path?: string;
  skillName?: string;
  evidence?: string[];
  sourceTraceIds?: string[];
}

export interface ClassifiedMemory {
  candidateId: string;
  level: MemoryLevel | 'DROP';
  title: string;
  memoryText: string;
  reason: string;
  confidence: number;
  keywords?: string[];
  language?: string;
  domainScope?: string;
  scope: {
    domain?: string;
    path?: string;
    skillName?: string;
    taskType?: string;
  };
}

export interface MemoryRefRecord {
  id: string;
  level: MemoryLevel;
  title: string;
}

export interface TaskMemoryCommitInput {
  goal: string;
  finalState: {
    total_history?: any[];
    long_term_memory?: { summary?: string };
    experience_buffer?: TaskExperienceBuffer;
    meta_data?: Record<string, any>;
    status?: string;
    planner_output?: { action?: Record<string, any> };
  };
}

export interface TaskMemoryCommitResult {
  taskRunId?: string;
  taskRunSynced?: boolean;
  scheduled?: boolean;
  experienceStatus?: 'PENDING' | 'RUNNING' | 'SUCCEEDED' | 'FAILED';
  candidates: number;
  committed: {
    L1: number;
    L2: number;
    L3: number;
    DROP: number;
  };
}

export interface RawTraceRecord {
  traceId: string;
  taskRunId: string;
  timestamp: number;
  stepIndex: number;
  nodeName?: string;
  actionType?: string;
  skillName?: string;
  success?: boolean;
  url?: string;
  domain?: string;
  path?: string;
  pageTitle?: string;
  stepSummary?: string;
  errorMessage?: string;
  memoryRefs?: MemoryRefRecord[];
  syncStatus?: 'pending' | 'synced' | 'failed';
  syncError?: string;
  syncRetryCount?: number;
  lastSyncAttemptAt?: number;
  syncedAt?: number;
  updatedAt?: number;
  raw: any;
}

export interface MemoryWriteResult {
  level: MemoryLevel | 'DROP';
  ref?: MemoryRefRecord;
}

export interface TaskRunRecord {
  id: string;
  goal: string;
  status: string;
  startedAt: number;
  finishedAt: number;
  hostUrl?: string;
  hostTitle?: string;
  globalSummary?: string;
  traceCount: number;
  candidateCount: number;
  committedL1: number;
  committedL2: number;
  committedL3: number;
  droppedCount: number;
  localPersistStatus: 'saved';
  experienceStatus: 'PENDING' | 'RUNNING' | 'SUCCEEDED' | 'FAILED';
  experienceStartedAt?: number;
  experienceFinishedAt?: number;
  experienceError?: string;
  experienceRetryCount: number;
  cloudSyncStatus: 'pending' | 'synced' | 'failed';
  cloudSyncError?: string;
  syncedAt?: number;
  updatedAt: number;
}
