/**
 * CoTabor Tri-level Memory Types
 * Definition for L1, L2, L3 and SyncQueue schemas
 */

// L1: Muscle Memory (DOM/Physical interactions)
export interface L1MuscleMemory {
  id: string; // e.g. mus_1001
  domain: string; // Target domain, e.g. github.com
  pathPattern: string; // Target path pattern, e.g. ^/pulls/.*
  elementSelector: string; // DOM Hash or Selector
  actionType: 'click' | 'input' | 'scroll' | 'hover' | 'wait' | string;
  physicalInstruction: string; // JSON string of execution parameters (e.g. CDP offset)
  reason?: string; // AI generated reason for the rescue
  executionCount: number; // Total times triggered
  successCount: number; // Times execution succeeded
  updatedAt: number; // Timestamp
}

// L2: Skill Schema Memory (API parameter fixing rules)
export interface L2SkillMemory {
  id: string; // e.g. skl_2001
  skillName: string; // Tool/Skill name, e.g. feishu_create_doc
  parameterRules: string; // LLM combined string of rules to avoid errors
  errorHistory?: string; // Past real errors encountered
  status: 'active' | 'archived' | 'needs_review';
  updatedAt: number; // Timestamp
}

// L3: Tactical Memory (Macro SOPs)
export interface L3TacticalMemory {
  id: string; // e.g. tac_3001
  intentQuery: string; // Intent summary for vector matching
  tacticalRules: string; // The SOP steps
  scope?: string[]; // e.g. ['global', 'project_a']
  embedding?: number[]; // 2048-dim vector for Orama semantic search
  updatedAt: number; // Timestamp
}

// Unified Sync Queue Entry
export interface SyncQueueEntry {
  id: string; // UUID for the queue entry
  action: 'insert' | 'update' | 'delete';
  memoryLevel: 'L1' | 'L2' | 'L3';
  targetId: string; // The ID in the target table (mus_*, skl_*, tac_*)
  payload: any; // The full record data
  queuedAt: number; // Timestamp
  retryCount?: number; // Number of failed push attempts; entry dropped after 3
}

// Raw Trace (New experience generated by Cortex/Watchdog before distillation)
export interface RawExperienceTrace {
  id: string;
  memoryLevel: 'L1' | 'L2' | 'L3';
  context: Record<string, any>; // url, path, element, error message, etc.
  suggestedCorrection: string | Record<string, any>; // The fix applied
  success: boolean; // Did the fix work?
  timestamp: number;
}
